### ISSUE TITLE
Had a question on your .travis.yml

### ISSUE THREAD

**Issue by tasdikrahman** [Oefenweb/ansible-virtualenv#5]
Hey @tersmitten . 

I was going through your `.travis.yml` file and I was wondering what makes travis build for different versions of the ansible.

I could see that you are telling travis the different versions of ansible to test with by doing a 

```
env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.2.2.0
  - ANSIBLE_VERSION=2.2.1.0
  - ANSIBLE_VERSION=2.2.0.0
  - ANSIBLE_VERSION=2.1.5
  - ANSIBLE_VERSION=2.1.4
  - ANSIBLE_VERSION=2.1.3
  - ANSIBLE_VERSION=2.1.2
  - ANSIBLE_VERSION=2.1.1.0
  - ANSIBLE_VERSION=2.1.0.0
  - ANSIBLE_VERSION=2.0.2.0
  - ANSIBLE_VERSION=2.0.1.0
  - ANSIBLE_VERSION=2.0.0.2
  - ANSIBLE_VERSION=2.0.0.1
  - ANSIBLE_VERSION=2.0.0.0
  - ANSIBLE_VERSION=1.9.6
```

Also on this line 

```
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    | grep -q 'changed=0.*failed=0'
```

Are you making use of `$?` here? Could you explain the `grep -q 'changed=0.*failed=0'` part

Any help would be greatly appreciated. Thanks

**Comment by tersmitten** [comment]
`env` expands the matrix, [see](https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix), so we run `before_install`, `install` and `script` for all versions defined in `env`.

> Are you making use of `$?` here?

Yes, the return value of `grep -q`

> `grep -q 'changed=0.*failed=0'`

Checks that there are no changes (and failures) in a subsequent run, this is called `idempotency`. Only the first run should report changes.

I hope this explains your questions.

**Comment by tasdikrahman** [comment]
> env expands the matrix, see, so we run before_install, install and script for all versions defined in env

So if there would be something like `after_success` or `after_failure` (for eg.) after `script`. That would also be added up to the number of jobs if I am getting it correctly?

> Checks that there are no changes (and failures) in a subsequent run, this is called idempotency. Only the first run should report changes.

Ohh. So my hunch is that you are checking for this particular pattern in the logs. That's smart 💯 😄

Thanks for the help. Also, is your approach very similar to testing it out on docker up on travis?

**Comment by tersmitten** [comment]
> So if there would be something like after_success or after_failure (for eg.) after script. That would also be added up to the number of jobs if I am getting it correctly?

Yes

> So my hunch is that you are checking for this particular pattern in the logs

Standard out (`stdout`)

> Also, is your approach very similar to testing it out on docker up on travis?

Yes, but we run our test on Ubuntu (`trusty`). A similar approach using Docker can be found here:

https://github.com/geerlingguy/ansible-role-apache/blob/master/.travis.yml

You can also run tests on all supported platforms using the `Vagrantfile` (manually)

**Comment by tasdikrahman** [comment]
@tersmitten Yup. Will check it out. Thanks for the help 😄
